# Generated by Django 4.2.11 on 2024-05-28 05:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintask',
            fields=[
                ('maintask_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintask_name', models.CharField(max_length=30, unique=True)),
                ('state', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Maintask',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('subtask_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30, unique=True)),
                ('state', models.IntegerField(default=0)),
                ('end', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('maintask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_db.maintask')),
            ],
            options={
                'db_table': 'Subtask',
            },
        ),
        migrations.AddField(
            model_name='maintask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_db.userinfo'),
        ),
        migrations.CreateModel(
            name='Dailytask',
            fields=[
                ('dailytask_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=0)),
                ('end', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_db.userinfo')),
            ],
            options={
                'db_table': 'Dailytask',
            },
        ),
    ]
