# Generated by Django 4.2.11 on 2024-05-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintask',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='maintask',
            old_name='start_time',
            new_name='start',
        ),
    ]
