# Generated by Django 4.2.11 on 2024-05-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_db', '0002_rename_end_time_maintask_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='maintask',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='maintask',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='end',
            new_name='end_time',
        ),
    ]
