# Generated by Django 4.2.11 on 2024-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_db', '0003_rename_end_dailytask_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
