# Generated by Django 4.2.13 on 2024-06-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_db', '0004_alter_dailytask_end_time_alter_maintask_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='line_id',
            field=models.CharField(max_length=33, null=True, unique=True),
        ),
    ]
